### ISSUE TITLE
All Time Measurements Not working after latest update

### ISSUE THREAD

**Issue by sushibagel** [cmroche/OctoPrint-HomeAssistant#107]
![image](https://github.com/cmroche/OctoPrint-HomeAssistant/assets/2222713/7799ca83-7b80-4d54-9a1c-93d3d4338530)

I've tried restarting Home Assistant but for some reason after the latest update none of the Time Measurements seem to update in Home Assistant.

**Comment by mreditor97** [comment]
Sorry, I am just in the middle of a patch for this.

**Comment by sushibagel** [comment]
> Sorry, I am just in the middle of a patch for this.

No need to apologize, I appreciate your work and just didn't see an report of it yet.

**Comment by mreditor97** [comment]
I added it, however I found some additional warning so just improving those before resubmitting the pull. I'll tag it here once it is done. Thanks :)

**Comment by mreditor97** [comment]
The fix is ready and waiting now. It is fully working as expected on my end.
It would be great if you could confirm it works as expected on your end too by installing it, you can do it from my fork: `https://github.com/mreditor97/octoprint-homeassistant/archive/patch/print-time.zip`

**Comment by sushibagel** [comment]
> The fix is ready and waiting now. It is fully working as expected on my end. It would be great if you could confirm it works as expected on your end too by installing it, you can do it from my fork: `https://github.com/mreditor97/octoprint-homeassistant/archive/patch/print-time.zip`

Seems to be working. Print time is still showing "Unavailable" but it may be due to the fact that I had just started the print. I'll update if it doesn't populate. 

![image](https://github.com/cmroche/OctoPrint-HomeAssistant/assets/2222713/c4c0c88e-77b2-46fb-9816-e3ac7ddad944)

**Comment by sushibagel** [comment]
> The fix is ready and waiting now. It is fully working as expected on my end. It would be great if you could confirm it works as expected on your end too by installing it, you can do it from my fork: `https://github.com/mreditor97/octoprint-homeassistant/archive/patch/print-time.zip`

I just realized that print times with notifications now seem to be showing wrong (in seconds maybe?). 


![Screenshot_20230706-093059](https://github.com/cmroche/OctoPrint-HomeAssistant/assets/2222713/4e9aa4b1-1c38-45f0-9b20-c6a8eafbc6fc)
SDS

Here is the relevant code from the notification. 

![image](https://github.com/cmroche/OctoPrint-HomeAssistant/assets/2222713/df24efca-1fff-4a83-b0aa-ba3cf3e55481)

**Comment by mreditor97** [comment]
Unfortunately the time is provided in seconds now, as that is required for Home Assistant so that it can be put into a graph.

You should be able to sort this by adding `timedelta` into the template of your notification:
It should look something like this: `{{ timedelta(seconds=states('sensor.octoprint_print_time_left')|int(default=0)) }}`

This will do the conversion from seconds to a readable time for you. The same will be required of the `sensor.octoprint_print_time` as well.

**Comment by sushibagel** [comment]
> Unfortunately the time is provided in seconds now, as that is required for Home Assistant so that it can be put into a graph.
> 
> You should be able to sort this by adding `timedelta` into the template of your notification: It should look something like this: `{{ timedelta(seconds=states('sensor.octoprint_print_time_left')|int(default=0)) }}`
> 
> This will do the conversion from seconds to a readable time for you. The same will be required of the `sensor.octoprint_print_time` as well.

Makes sense. Thanks for the quick reply.

**Comment by mreditor97** [comment]
As a potential remedy to this, I could make it send the old timing method through as a attribute of the Print Time Left sensor? Would that be a good possible solution?

**Comment by sushibagel** [comment]
> As a potential remedy to this, I could make it send the old timing method through as a attribute of the Print Time Left sensor? Would that be a good possible solution?

I don't know that it's really necessary. Your solution worked. You may just want to add it to the documentation. 

![Screenshot_20230706-135551](https://github.com/cmroche/OctoPrint-HomeAssistant/assets/2222713/630c47b2-f781-4ece-9d0f-e781844872e4)

**Comment by mreditor97** [comment]
I believe you should be able to prettify it too, but I'll look into that.

I will add some documentation when I get chance. Glad it works for you!

**Comment by rozhkovets** [comment]
HomeAssistant Discovery (3.6.5) clean install
Home Assistant 2023.7.1

All time measurements stiil not working
log HA https://pastebin.com/0Q57zrYA

**Comment by mreditor97** [comment]
@rozhkovets The patch I have made is waiting to be pushed into the live version.

Can you try to install it manually, at the link provided above and let me know if that works for you?

Thanks!

**Comment by rozhkovets** [comment]
@mreditor97, its works, thanks

but, I noticed a strange thing, print time was unavailable and was updated after ending G29, at the same time other time measurements were updated immediately after i start of printing
