### ISSUE TITLE
Many attributes in binary_sensor.printing

### ISSUE THREAD

**Issue by rosenstand** [cmroche/OctoPrint-HomeAssistant#12]
Thanks for this great plugin! It's really nice with all the additional information over the official, local polling OctoPrint integration for Home Assistant. However I found that the some (most?) of the sensors carry a ton of attributes, which I'm afraid will fill the Home Assistant database. Is this right?

<img width="1840" alt="Skærmbillede 2020-06-22 kl  20 09 49" src="https://user-images.githubusercontent.com/749367/85326803-25e13400-b4ce-11ea-9245-dd2d69827f4e.png">
<img width="1840" alt="Skærmbillede 2020-06-22 kl  21 26 20" src="https://user-images.githubusercontent.com/749367/85327332-0bf42100-b4cf-11ea-8182-25695c3704db.png">

**Comment by cmroche** [comment]
This one structure is used in a couple of places, it's a bit offensive so I may remove it over the next couple of days. I have to review and consider if the attributes might be valuable first.

**Comment by cmroche** [comment]
After reviewing the attributes I'm going to make many changes, including removing all attributes from binary_sensor.is_printing and using attribute templates to simplify the printer status sensors. This should alleviate much of the problems with spamming the DB.
