### ISSUE TITLE
Not updating HA mqtt messages

### ISSUE THREAD

**Issue by patrickcollins12** [cmroche/OctoPrint-HomeAssistant#120]
I've installed Octoprint-MQTT and HA Discovery. It looks like, via MQTT Explorer the octoPrint mqtt entries are getting updated. HA Discovery creates the initial switches and sensors on startup, but then none of the values ever update. I can use the switches installed, but again, they never update their state. How can I debug what is going wrong here?
![image](https://github.com/user-attachments/assets/5366d393-f0ee-44c6-a4a2-3c4cd2eef38a)

**Comment by patrickcollins12** [comment]
ok, this is weird, now they're suddenly updating. I have no idea why it took an extended period of time to start updating. Feel free to close unless you see a potential bug here.

**Comment by TheRealFalseReality** [comment]
Now mine aren't updating...
