### ISSUE TITLE
Support for Homing, Jogging, and other GCODE commands

### ISSUE THREAD

**Issue by XRyu** [cmroche/OctoPrint-HomeAssistant#15]
Hi, would be great if you could some more switches:
- Connect-Switch
- Axis-Movements
- Axis Homing

**Comment by cmroche** [comment]
Hey, thanks for the suggestions.

It's pretty easy to add new switches, I had wondered if connectivity and homing would be valuable, but I'll admit that I had a hard time imagining that someone would want to control these from Home Assistant, are you using some kind of workflow that fully prevents you from using the OctoPrint interface? Could you tell me a bit more about how you working that makes these commands valuable?

**Comment by XRyu** [comment]
Hey, of course :)

Nah, i am not absolutely preventing to use Octos Frontend, but i like to use my dashboard, which is also available through any Browser even outside from my Network to control my printer from to go when out of the house. ;)
I am using an automation from HA too, to connect Octoprint (running always) to the printer, when i turn the connected socket on :)

My Dashboard looks like this, currently:
<img width="1183" alt="Bildschirmfoto 2020-06-25 um 23 22 03" src="https://user-images.githubusercontent.com/131995/85796726-b8860b00-b73a-11ea-944e-7afc0f7076c6.png">

**Comment by XRyu** [comment]
And i just love having as much information as possible in a compact matter on my Dashboard, and looking a little less technical than my Octo-Frontend :)

**Comment by cmroche** [comment]
Thanks for sharing. So the only potential catch here is that it might be best for the job functions to be implemented as a script, then it could pass the distance to jog. The downside is that the script would need to be created by you, and setup to call to MQTT.publish, giving the topic, perhaps something like `octoPrint/hassControl/jog` with a payload like `{"x": 10}`. Scripts cannot be configured automatically, so even though I would still need to add the topic you would need to add the service in your HA configuration.

The alternative would be to create and publish a "SWITCH" device which when turned on would jog, but then the distance wouldn't be customizable, I would have to hard code a value in the MQTT device configuration. For Home this is less of an issue, the behaviour is fixed based only on the axis.

If you had to make the choice, which route would you prefer, and why?

**Comment by XRyu** [comment]
I think i would prefer the way Octoprint itself does it, having the Jogs available for the fixed values 0.1/1/10/100 for all axes. not having to script anything more than needed :)

**Comment by cmroche** [comment]
I agree, but that's an awful lot of switches to create and register on the device (12 for jog + 2 for home). However, those buttons could be created directly in the UI with little effort, and offer more flexibility.

Each button, something like this.

```yaml
type: entity-button
name: X 0.1
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: "octoPrint/hassControl/jog"
    payload:
      x: 0.1
```

**Comment by cmroche** [comment]
Giving this a bit more though, I would probably go a bit more generic. Create a single topic that could receive GCode commands directly. This would allow for any amount of specialized behaviour on the UI. Even baby stepping if you want to go that far :)

**Comment by XRyu** [comment]
Hmm, i like both approaches. I am more for the simplicity of the specific jog-action with parameters like x: 0.1 . as pure GCode again gets really technical and i personally find it easier to read some clear payload rather than a gcode :)

But the Addition to post ANY gcode to mqtt is also a VERY powerful function for any special cases :)

**Comment by cmroche** [comment]
@XRyu I've submitted an MR with the changes, and examples, to support homing, jogging and other GCODE commands. You can manually install this branch in octoprint using this URL https://github.com/cmroche/OctoPrint-HomeAssistant/archive/jogging.zip

If you are able to test this, please let me know, provide feedback directly on the pull request #17
