### ISSUE TITLE
Cannot see in Octoprint plugin manager

### ISSUE THREAD

**Issue by Taomyn** [cmroche/OctoPrint-HomeAssistant#2]
It's not showing up for me when looking for plugins in OctoPrint, could it be because the link could be wrong like it is here on the main Github page?

`https://github.com/cmroche/OctoPrint-HomeAsisstant/archive/master.zip`

Should be

`https://github.com/cmroche/OctoPrint-HomeAssistant/archive/master.zip`

![image](https://user-images.githubusercontent.com/4365929/84753486-57826880-afbf-11ea-8e4c-dd5efe3e8f90.png)

**Comment by Taomyn** [comment]
Weird, I had already restarted OctoPrint a short while earlier, then after the MQTT plugin and restarting it again, it was showing up in plugin-manager.

Still, the link is wrong anyway.

**Comment by W-Floyd** [comment]
Resolved in 41b1ebbc8e6bf2d6676850149d0e5152f27d52f5

**Comment by cmroche** [comment]
Yeah happened to try this in a small windows where it was broken :) Sorry about that. Let me know if you have any more issues, and thanks for the report.
