### ISSUE TITLE
Better names and icons for time

### ISSUE THREAD

**Issue by rosenstand** [cmroche/OctoPrint-HomeAssistant#21]
Wow you're making fast progress on this project. It's a real joy to follow.

Subjectively I think the icons for "print time"/"print time left" are a little too different. (Also if they were named "time elapsed"/"time remaining", it would be name-compatible with the built-in OctoPrint integration, which means users moving to/from this plugin would not need to change them... just a thought :))

Personally I've changed the icon for "print time left" to mdi:clock-end which I think matches "print time" (mdi:clock-start) better. It's also used by polling OctoPrint IIRC.

**Comment by rosenstand** [comment]
Uh, also I think mdi:axis-z-arrow would fit the Z axis better than the nozzle :)

**Comment by rosenstand** [comment]
That way you could use mdi:printer-3d-nozzle for tool temperature, and mdi:radiator for the bed. ... ok I'll stop myself now :)

**Comment by cmroche** [comment]
:) Thanks for the feedback.

I like the suggestions you made, I'll incorporate them soon.
