### ISSUE TITLE
Send SoC temperature to home assistant

### ISSUE THREAD

**Issue by PieKiu** [cmroche/OctoPrint-HomeAssistant#23]
Hi,

this is not an issue. Your Plugin works great and makes for a tremendous addition to my home assistant setup.

Would it be possible to send the SoC temperature to Home Assistant as well? I would really appreciate that.

Thank you,
Paolo

**Comment by cmroche** [comment]
I assume it's possible, but I'd need to investigate.

**Comment by cmroche** [comment]
I looked into how to do this, it's not complex at all, just not as trivial as reading an attribute from some existing data structure.

I'll likely add this over the next week or two, I need to finish up something else I am working on first.

**Comment by pqanalyst** [comment]
Wow, that is great!

Thank you very much,
Paolo

**Comment by cmroche** [comment]
Just a heads up, I am working on this slowly.. next weekend though I need to figure out how to do on device debugging since this feature actually only works directly on the pi. I'll let you know when there is something ready for testing, maybe another 2 weeks.... basically as time permits.

**Comment by PieKiu** [comment]
Hi cmroche,

Any progress on this one? Still looking forward for it.

**Comment by cmroche** [comment]
Yes, but it is going slowly as I am a bit time constrained at the moment.
