### ISSUE TITLE
Can't use print file as a sensor in home assistant

### ISSUE THREAD

**Issue by admawby** [cmroche/OctoPrint-HomeAssistant#27]
I tried setting up a card in lovelace similar to yours, but ran into a snag when i tried to add the Print File sensor - it is not defined in the Home Assistant integration so it throws an error. is MQTT required for the print file name or am i missing something with the direct integration?

**Comment by cmroche** [comment]
Yes, this plugin requires MQTT to be configured to work. This applies to all sensors.

If you do not want to use MQTT you will need to use the HomeAssistant provided integration, and configure your OctoPrint server and API keys manually. [Integration](https://www.home-assistant.io/integrations/octoprint/)

I presume that you do not have MQTT configured, so this is more of a question than a bug report, is that correct?

**Comment by admawby** [comment]
correct, I have not configured this with my MQTT server. I have configured the HA integration with the octoprint API keys and wanted to confirm that the file name sensor is not included in that integration. It would be very helpful to add the configuration.yaml entries in the readme that are required for the switch entities you are using in your Lovelace example.

**Comment by cmroche** [comment]
This project is only for the MQTT integration, the project doesn't require (or have) a setup in the configuration.yaml. The only requirement is that an MQTT broker be configured on your HA setup--this is done through the "Supervisor" panel.

The reason I built this plugin for OctoPrint was to have a way to auto-configure the devices through MQTT, and not require a setup in configuration.yaml avoiding the HA native OctoPrint integration. For this reason the examples won't reflect sensors provided from an HA native integration.

**Comment by admawby** [comment]
Understood! My misundertanding then. Thanks for the replies anyways.

**Comment by cmroche** [comment]
No worries :)

Give MQTT a try though, I think you will find this approach superior in many way, and HA has great support for MQTT.
