### ISSUE TITLE
Supporting multiple instances of OctoPrint

### ISSUE THREAD

**Issue by Rad3d21** [cmroche/OctoPrint-HomeAssistant#29]
Would it be possible to implement support for multiple instances ?
Right now it is 1 printer, 1 octoprint. I'm running multiple instances on the same rpi. It would be nice to differentiate between them.  At the moment it will randomly show one of the printers entries, whichever logs last.

**Comment by XRyu** [comment]
I think you just need to change the Base-Topic in the
MQTT-Plugin's Settings :)

Am Mo., 13. Juli 2020 um 22:23 Uhr schrieb Rad3d21 <notifications@github.com

**Comment by Rad3d21** [comment]
Hmm. tried that but it did not show in home assistant. Just kept the octoprint and I saw octoprint_2 but not the octoprint_x1

**Comment by Rad3d21** [comment]
It picked up the first change of the base_topic. I can see that in home assistant. It shows subscribed to the new name. However the second instance it did not pick up.

**Comment by cmroche** [comment]
Hi Rad, sorry to hear you are having trouble. Dual instances is not something I've explicitly tested (yet) though in theory it should be feasible. There are a couple of things to work out.

1) As mentioned by @XRyu please check the the base topic in each instance is unique.
2) Verify that the config.yaml for each instance has a unique UUID

Once verified and changes, delete the device(s) from HA then restart the servers for both instances, this will reregister the devices.

My understand of the HA device registry, this should be sufficient to have both instances working correctly, please let me know how that goes. If you have further problems attach configs from each octoprint instance, then in HA in `Config -> Device -> [The Device] -> MQTT Info` show me the payload for the first device configuration. See the image below

![image](https://user-images.githubusercontent.com/1007595/87453196-2dc55d00-c5d0-11ea-9791-5bd212f0a2f1.png)

**Comment by Rad3d21** [comment]
![image](https://user-images.githubusercontent.com/43404751/87475198-a2c28200-c624-11ea-8522-7edebf6dbed9.png)

**Comment by Rad3d21** [comment]
That matches the first 6 characters of the ID of the first octoprint config.yaml. I restarted the octopi and also home-assistant. (upgraded it from 111.4 to 112.4 to have the most current just in case)

**Comment by cmroche** [comment]
@Rad3d21 thanks, a few more questions

1) What were the base topic names you used for instance 1 and 2?
2) Start both instances, what values do you have when you subscribe to `<base_topic>/mqtt` for both instances. I'm expected the retained status to be "connected" in both cases. Easiest way to check is with mosquitto_sub, but tools like MQTT.fx will work just as well.

For my future easy reference:

1st instance, octoPrint-A10, c1ce63ec-f52d-43d0-a3ad-db3ccb228905
2nd instance, ????, 5031e39b-8e33-4f74-8104-069a5c613f76

**Comment by cmroche** [comment]
Actually if you could attach the two config file it would really be a big help, remove credentials/API keys, etc. My GPG public key is attached if you prefer, and can be validated on keys.openpgp.org

**Comment by Rad3d21** [comment]
Ok. I removed the octoprint device from home assistant. Rebooted the octopi completely so it would register everything from start. Now it does show 2 instances in home assistant. I guess it was necessary to remove the device from home assistant before it understood the second printer from octoprint. (I already rebooted octopi but that on itself did not solve the issue)

**Comment by cmroche** [comment]
@Rad3d21 great to hear it worked out then! I'm going to re-open this as a reminder to add some notes to the readme.md about supporting multiple instances. Thanks for the information you provided.
