### ISSUE TITLE
Cannot shutdown since updating Octoprint to python 3

### ISSUE THREAD

**Issue by pinkywafer** [cmroche/OctoPrint-HomeAssistant#36]
Log reports: 
```
octoprint.plugins.homeassistant - INFO - Unable to run shutdown command: __init__() got an unexpected keyword argument 'async'
```
have the params changed?

**Comment by jan-hendrikscholz** [comment]
Hi @pinkywafer 

Seems @gpambrozio already found the reason and proposed a solution via pull request for it.

Let's see, if the PR will be merged soon :-)

**Comment by cmroche** [comment]
I believe this is fix and will be in the next update. I'll test and push a release this weekend.

**Comment by cmroche** [comment]
Should be part of release 2.2.1

Thank you for the report & contributions @pinkywafer  @gpambrozio
