### ISSUE TITLE
Only one device discovered

### ISSUE THREAD

**Issue by mirek251** [cmroche/OctoPrint-HomeAssistant#4]
I am running two instances of Octoprint on one server managing two printers. But only one device is discovered in HA (last connected).

**Comment by cmroche** [comment]
The likely reason is that you are using the same topic for both printers in your MQTT configuration.

Make sure this path is unique for both running instances of octoprint.

![image](https://user-images.githubusercontent.com/1007595/85185534-502eb980-b262-11ea-97df-b0a9e80b1ac5.png)

**Comment by cmroche** [comment]
Actually it dawned on me, there may be another issue here. The unique id for the device is stored in the octoprint configuration file. Do you use the same configuration file when running multiple instances?

**Comment by rosenstand** [comment]
I bumped into this issue as well. I've had the MQTT plugin installed for a long time, but just started using it with your integration. I imagine a lot of people will do the same, so maybe it could be noted in the docs/README?

**Comment by mirek251** [comment]
I use different config for each instance. So I assume UUID is unique, as well.

**Comment by cmroche** [comment]
> I use different config for each instance. So I assume UUID is unique, as well.

Could you share the config files please. Don't forget to redact IPs and credentials.

**Comment by cmroche** [comment]
I'm going to close the issue for now since there has been no response, but if you get the opportunity to provide the configurations for an erroneous setup please feel free to add them and re-open.
