### ISSUE TITLE
Possible to add printTimeLeft (not formatted)?

### ISSUE THREAD

**Issue by nibblerrick** [cmroche/OctoPrint-HomeAssistant#41]
I like to have the estimated time displayed in home assistant when the print is finished.
I tried to use the printTimeLeftFormatted, but using the formatted time in a template is a little messy.
When I make an extra mqtt-sensor in HA with printTimeLeft I can easily calculate the now-timestamp plus the seconds of the sensor.
So my question is: Could you include the printTimeLeft in the ha-sensors? Doesn't have to be a sensor, as attribute it would be sufficient.
If the ETA (should be ETF - estimated time finished in this context) is directly possible to include it would be nice, too, but I don't know if that's availible.

And not to forget: very nice plugin, thanks!

**Comment by cmroche** [comment]
I don't see why not, but I would likely add this as an attribute to the print time left sensor, and not it's own sensor as I've generally done this with unformatted timestamps.

**Comment by cmroche** [comment]
Added on 29830e339819da6b39a57a830462e1646635e622

**Comment by nibblerrick** [comment]
As an attribute would be totally fine.
In the commit however I only see PrintProgress % but not unformatted time. Am I overlooking sth.?

**Comment by cmroche** [comment]
Yes, so the property was already being pushed to MQTT, in part of a larger status post too "hassTopic"/printing, under a key called "progress". This change assigns that dictionary to the attributes of this sensor, it will contain all information from the progress dictionary, including the one you are looking for.

**Comment by nibblerrick** [comment]
Found it, thanks.
I have an sensor.octoprint_e5p_print_progress (where e5p for the printer) and there aren't any attributes.
But at sensor.octoprint_print_progress are the attributes I was missing.
Perfect, thanks again for this fast implementation!
