### ISSUE TITLE
Formatting Of "estimatedPrintTimeFormatted"

### ISSUE THREAD

**Issue by james-jutras** [cmroche/OctoPrint-HomeAssistant#45]
"estimatedPrintTimeFormatted" is being formatted as "0:25:12.647860", where as "printTimeFormatted" is being formated as  "0:35:58" and "printTimeLeftFormatted" formated as "0:00:00". I believe the fractional second portion should be truncated/rounded. Excellent plugin!

**Comment by cmroche** [comment]
I cannot say I've seen this... could you give me the full MQTT message for this sensor. You should be able to get this through MQTT Info in HA for the device, or through an MQTT client.

**Comment by james-jutras** [comment]
Here’s the actual MQTT post for octoPrint1/hass/printing acquired via the “MQTT Explorer” client on my PC (http://mqtt-explorer.com/):

 

{"_timestamp": 1603658754, "offsets": {}, "job": {"estimatedPrintTimeFormatted": "0:20:36.520475", "averagePrintTime": 1914.6477377210394, "lastPrintTime": 1914.6477377210394, "user": "_admin", "file": {"origin": "local", "name": "Cable_Holder_0.2mm_PETG_MK3S_26m.gcode", "date": 1603653343, "path": "Cable_Holder_0.2mm_PETG_MK3S_26m.gcode", "display": "Cable_Holder_0.2mm_PETG_MK3S_26m.gcode", "size": 729858}, "estimatedPrintTime": 1236.5204745240453, "filament": {"tool0": {"volume": 2.6517184695023808, "length": 1102.456430000011}}}, "state": {"text": "Operational", "flags": {"cancelling": false, "paused": false, "operational": true, "pausing": false, "printing": false, "resuming": false, "sdReady": true, "error": false, "ready": true, "finishing": false, "closedOrError": false}}, "currentZ": 42.6, "progress": {"completion": 100.0, "filepos": 729858, "printTimeFormatted": "0:27:53", "printTimeLeftFormatted": "0:00:00", "printTimeLeft": 0, "printTime": 1673, "printTimeLeftOrigin": null}}

 

 

Via HASS:

 

Received 9:35:32

*	QoS: 0, Retained
*	Payload: 

·         _timestamp: 1603658754

·         offsets: {}

·         job:

·           estimatedPrintTimeFormatted: '0:20:36.520475'

·           averagePrintTime: 1914.6477377210394

·           lastPrintTime: 1914.6477377210394

·           user: _admin

·           file:

·             origin: local

·             name: Cable_Holder_0.2mm_PETG_MK3S_26m.gcode

·             date: 1603653343

·             path: Cable_Holder_0.2mm_PETG_MK3S_26m.gcode

·             display: Cable_Holder_0.2mm_PETG_MK3S_26m.gcode

·             size: 729858

·           estimatedPrintTime: 1236.5204745240453

·           filament:

·             tool0:

·               volume: 2.6517184695023808

·               length: 1102.456430000011

·         state:

·           text: Operational

·           flags:

·             cancelling: false

·             paused: false

·             operational: true

·             pausing: false

·             printing: false

·             resuming: false

·             sdReady: true

·             error: false

·             ready: true

·             finishing: false

·             closedOrError: false

·         currentZ: 42.6

·         progress:

·           completion: 100

·           filepos: 729858

·           printTimeFormatted: '0:27:53'

·           printTimeLeftFormatted: '0:00:00'

·           printTimeLeft: 0

·           printTime: 1673

  printTimeLeftOrigin: null

 

 

James

**Comment by cmroche** [comment]
Thanks. I'll take a look at it over the next couple of days.

**Comment by cmroche** [comment]
Sorry it took so long to Geta around to this, but the microseconds should be removed now on version 3.2.1
