### ISSUE TITLE
only one instance at a time 

### ISSUE THREAD

**Issue by NinDTendo** [cmroche/OctoPrint-HomeAssistant#48]
Might be related to #29 

I am trying to get my 2 instances of Octoprint recognized by HA.
Both instances have a different `base topic` and I made sure that the `Node ID` is unique per instance/printer.

The payloads (in HA "MQTT Info) confirm that the `unique_id` and `state_topic` are unique as well. Only the "connections:" part is identical.

I do manage to connect both, but not at the same time. 
Additionally the printers are not recognized as individual devices, which I would prefer to have for better organizing.

Unfortunately I have no idea how to print logs, since I'm not that familiar with linux commands. But can provide if someone sends me the commands for it.

I have tried the solution provided in #29 already with no success. (restarted HA, and both instances- individually and together)

**Comment by cmroche** [comment]
Could you paste the payloads please, and what do you mean by the "connections: part"?

Thanks.

**Comment by NinDTendo** [comment]
![image](https://user-images.githubusercontent.com/3543456/98151165-0c1a1980-1ed0-11eb-83de-85aff0f8eeaf.png)
![image](https://user-images.githubusercontent.com/3543456/98151245-281dbb00-1ed0-11eb-95bc-11065c2579e1.png)

This is what I mean by "connection:"
![image](https://user-images.githubusercontent.com/3543456/98151284-38359a80-1ed0-11eb-989e-f46578cdb8cb.png)

**Comment by cmroche** [comment]
Hmmm, maybe the connections is causing an issue. Though I would expect this to lead to 1 devices, but with sensor duplicated for each instance. Can you show me the list of sensors you have under the working device?

**Comment by NinDTendo** [comment]
It's somewhat of a hit and miss... just earlier all sensors got recognized and worked parallel, after a reboot only 1 instance is working correctly.
But as u pointed out in your edit too, I would expect two different devices (which is not the case). Currently only the 2nd instance got recognized, I will post the list of sensors later if the first instance ever gets recognized again.

For now at least now the 2nd sensor (alone) is working fine.
![image](https://user-images.githubusercontent.com/3543456/98169117-f9add900-1eeb-11eb-8e12-e78b8129f995.png)

**Comment by NinDTendo** [comment]
on a sidenote, I think u need to change the camera platform to mjpeg instead of generic in the readme

```
camera:
  - platform: mjpeg
    name: OctoPrint Ender 3
    still_image_url: http://octoprint.local/webcam/?action=snapshot
    stream_source: http://octoprint.local/webcam/?action=stream
```

**Comment by cmroche** [comment]
You have two separate devices registered, so it looks like the config is good, and they do work sometime so the data is getting to the right topics.

Have you checked the MQTT topics for both printer to see what is being posted there, and if they are both updating?

**Comment by NinDTendo** [comment]
They are usually both registered as either the geeetech a10 OR the anet a8.
(1 device with sensors from both instances)

I am not sure how to check the topics tbh.

**Comment by cmroche** [comment]
You can use any MQTT client, like http://www.jensd.de/apps/mqttfx/1.7.0/ to subscribe to path you see in `state_topic` in both screenshots. With this you will see all the messages being sent to home assistant and will verify if the octoprint is 1) sending messages to both topics at the same time and 2) what messages are being sent.

**Comment by NinDTendo** [comment]
![image](https://user-images.githubusercontent.com/3543456/98240372-995d7c80-1f69-11eb-9e79-2756358e245a.png)
Managed to get both working again.
But they are still 1 device ...

**Comment by cmroche** [comment]
https://developers.home-assistant.io/docs/device_registry_index/

According to this, it's due to the mac address.. so I think this gives an easy way to solve the problem. I'll take a look at it once I have a moment to reread and test this.

**Comment by cmroche** [comment]
@NinDTendo Would you try the following please:

1. Uninstall the plugin and shutdown octoprint
2. Delete the device from HomeAssistant
3. Reinstall the plugin from this URL: https://github.com/cmroche/OctoPrint-HomeAssistant/archive/fix-multi-instance-20201105.zip

I think this might fix your issue, please confirm and I'll merge the fix.

**Comment by NinDTendo** [comment]
Just tested, 
works as intended so far! Thanks for the help and quick fix!

**Comment by rogodra** [comment]
Hello,

I have the same problem or similar, I have 3 raspberrypi, each with two instances of octoprint, a total of 6 printers. In Home Assistant it detects the 6 printers separately, each with its own sensors.

sensor.octoprint_tool_0_temperature
sensor.octoprint_2_tool_0_temperature
...

So far so good, the problem is that the sensors are like fused, that is, they all mark the same, for example, if I put one printer to heat to 40º, the other to 60º and a third to 80º, all sensors they are marking the 3 values, when each sensor would have to mark only the one of its printer.


![Snag_1aef228a](https://user-images.githubusercontent.com/26087556/140793208-1a1cf5b0-3cd2-4164-ac58-ec5dd646629d.png)

Same with all sensors or switches, another case, if I connect a printer, the action is done on all 6 printers.

What can I be doing wrong?

Thanks,
