### ISSUE TITLE
Autodiscovery in Homeassistant not working?

### ISSUE THREAD

**Issue by Invento3D** [cmroche/OctoPrint-HomeAssistant#49]
Hello,

I setup everything according to instructions, and I can see the relevant topics on my HA Broker:
![grafik](https://user-images.githubusercontent.com/27298166/98276060-b9a33080-1f95-11eb-9ed2-211e7b40f821.png)

However, the Printer does not get automatically discovered within Homeassistant. I run Homeassistant in an LXC Container based on Ubuntu 20.

The config of my MQTT integration also shows that auto-discovery is enabled (I think):
<img src="https://user-images.githubusercontent.com/27298166/98276201-eb1bfc00-1f95-11eb-9b90-8defec2fc2a4.png" width="500">
I also tried adding
```
mqtt:
  discovery: true
```
to `configuration.yaml` without success.

**Comment by Invento3D** [comment]
It works now. A restart of OctoPrint was not enough, I had to restart the system.

**Comment by derandiunddasbo** [comment]
I also ran in this issue and spent about 10 minutes to figure out, why the OctoPrint device was not discovered from HA after installing this plugin. 

Please at least mention in the setup section, that a system restart is or may be required after installing the plugin to activate it. This could spare new users some precious lifetime. ;-)
