### ISSUE TITLE
Group-entitie with things from OctoPrint Auto-discovery

### ISSUE THREAD

**Issue by exetico** [cmroche/OctoPrint-HomeAssistant#53]
Hi,

_I know it's a bit off the main topic of this feature-set, but I'll try_ :-)

What are the best way to create a Home Assistant group-entities, with all entities added from this auto-discovery solution? I'm not sure if there's a fast way to do it, without manually having to update the group, if something changes down the line.

So; Hit me with your suggestion if you have one :-)

**Comment by cmroche** [comment]
@exetico The HA forums would be a better place for an answer to this, as I have to admit that I am not that great in term of knowledge of Lovelace.

If I had to guess though, current entity grouping cards are too simple for what you want... they would probably add everything, or not enough. If you have a card layout in mind for your group, you could create a custom card component to achieve this. There are probably a few examples on hacs if you look around.

**Comment by cmroche** [comment]
I'm going to close the issue though since it's sort of off topic from this project. If you disagree, let me know.

**Comment by exetico** [comment]
Well, that's fair - i guess. My question was if it was possible to group all the entities together - but sadly that's not an option in the Auto Discovery-scope in HA. They should really start grouping Auto Dicovery elements like that, in grops, mapped to a "autoentities"-group for each auto-discovery component, or something like that.  I'll suggest it, in the HA Community.
