### ISSUE TITLE
entities in Home Assisten are unavailable 

### ISSUE THREAD

**Issue by DariBer** [cmroche/OctoPrint-HomeAssistant#58]
I have problem to get the plugin HomeAssistant Discovery in OctoPrint to work with my Home Assistant.

I can see all the Entity ID in Home Assistant, but status for all of them are unavailable 
Has anyone had this problem?

**Comment by cmroche** [comment]
Duplicate of #55 please check the discussion there.

**Comment by cmroche** [comment]
Since there has been no other activity, I will close the bug now. If you think this is in error please let me know.
