### ISSUE TITLE
feature request - G-Code + Camera

### ISSUE THREAD

**Issue by coolduke666** [cmroche/OctoPrint-HomeAssistant#59]
appreciate all your work and your plugin works like a charm. I am using currently your plugin as well as the homeassistant octoprint integration.

to get rid of the HA integration, two things are missing:
a) send G-Code to octoprint, eg. to turn off the enclosure light,
b) setup the octoprint camera as HA camera (don't know if this is possible via MQTT)

Thanks

**Comment by cmroche** [comment]
Thanks for the feedback.

1) Actually sending GCode is already possible, check the examples on the front page of the repostory (https://github.com/cmroche/OctoPrint-HomeAssistant#send-gcode-from-lovelace)

2) Camera configuration from MQTT isn't possible, unfortunately. Rather, it isn't a feature supported yet by the MQTT integration in Home Assistant. However, you can configure the video feed directly in your configuration.yaml, again check the examples on the front page (https://github.com/cmroche/OctoPrint-HomeAssistant#send-gcode-from-lovelace) (though use mpeg platform, not generic, I need to update that).

**Comment by cmroche** [comment]
Since there isn't any action that can be taken on the request at the current time, I'm going to close this issue.
