### ISSUE TITLE
Estimated Finish Time

### ISSUE THREAD

**Issue by dwoosnam** [cmroche/OctoPrint-HomeAssistant#61]
I love the effort that's gone into this, so thank you for your time and efforts. I wondered if it would be possible to create a sensor that gives an estimated finish time? This might make it easier to be around for longer prints when they finish. The equation seems easy, but the code not so much for me, in the plugin or Home Assistant.
StartTime + EstimatedRemaining = FinishTime
Thanks

**Comment by cmroche** [comment]
Hi @dwoosnam 

Thanks for the suggestion. I have to admit, I'm not 100% certain if this should be a sensor added to this plugin vs. building a template sensor to provide the information. Since it would be a duplication of information that is essentially present, and adding it would add more data into the database for the device. The flip side is that it is convenient so I'm willing to consider it is users find this valuable in general.

While I think this over, have you considered using a template sensor instead?

**Comment by sbelongie** [comment]
I would love to have this added.  If not a least provide a template sample for people who would want to have this.  I am trying to work on a template but I am having an issue with it

**Comment by sca075** [comment]
Hope this can help.. I just made it and give you the remaining time based on current time. if "Unavailable" it set "00:00:00", I´m currently trying to get it in the format (example) 1 day 2 hours 25 minutes but for instance when hours is more than 24 days is show.

    # Printer Remaining Time
    # Check if the value is null and perform date diff with actual time
    3d_printer_remain_time:
      friendly_name: "Remaining AMK8 time"
      unit_of_measurement: "timestamp"
      value_template: >
        {% set f = as_datetime(states("sensor.octoprint_estimated_finish_time")) %} 
        {{'00:00:00' if f == None else 
        (float(f) - float(now())) }}

**Comment by sca075** [comment]
P.s. it should be a sensor in HA configuration or the yaml file you use ;)

**Comment by sbelongie** [comment]
Thanks you I will check it out this weekend

**Comment by sca075** [comment]
No problem ;) .. by the way I got the notification script too.. it means once you have the sensor for the remaining time active you can use the following template to "split" the time in your notification service. I did try it with my TTS notification  and also this is working..

{% set t = states("sensor.3d_printer_remain_time").split(':') %}
{% if (t[0]|int // 24) > 0 -%}
 {{t[0]|int // 24}} days, {{t[0]|int % 24}} hours, {{t[1]}} minutes, {{t[2]}} seconds
 {% elif (t[0]|int % 24) > 0 -%}
 {{t[0]|int % 24}} hours and {{t[1]}} minutes.
 {% elif t[1] > 0 -%}
  in {{t[1]}} minutes. 
{%- endif %}
