### ISSUE TITLE
Question: Get status from Filament Manager

### ISSUE THREAD

**Issue by klec00** [cmroche/OctoPrint-HomeAssistant#66]
Is it possible to also get an indication of the selected filament from e.g. filament manager plugin? Would be great if a HA sensor could keep track of that.

**Comment by edekeijzer** [comment]
For this to work, the other plugin should expose helpers and/or hooks so the HA plugin can get the information. I've checked the filament manager source and that doesn't have either of these.

**Comment by cmroche** [comment]
Thanks @edekeijzer for the resposne.

I'm going to close this since it isn't actionable. If that changes @klec00 feel free to re-open the issue and we can look at it again.
