### ISSUE TITLE
Auto-shutdown once the printer has cooled down guide

### ISSUE THREAD

**Issue by Walmtech** [cmroche/OctoPrint-HomeAssistant#69]
Hi I notice you have an example automation to call the safe shutdown. 
In this automation you disable the automation after it's run:

    - data: {}
      entity_id: automation.printer_ender_3_shutdown_when_cool
      service: automation.turn_off

Can we also have the automation that re-enables this added to the readme as this will provide the full solution.

Thanks

**Comment by cmroche** [comment]
@Walmtech in this case you can simply remove this step. The only reason I do this is that I usually want my printers to stay running, and only wants the shutdown on occasion. So once the shutdown happens the automation resets to the original state, this reset is not critical if you don't want the behaviour so simply removing the step should suffice.
