### ISSUE TITLE
switch.ender3

### ISSUE THREAD

**Issue by michalk-k** [cmroche/OctoPrint-HomeAssistant#70]
HA sources found in documentation refers switch.ender3 switch:
- in Lovelace code
- in the script
 
However it's not being created by MQTT discovery. Also it's not mentioned the documentation. What should be the function of this switch?

**Comment by LRTNZ** [comment]
I think that might be a custom power switch they have hooked upto their printer?

**Comment by yasars** [comment]
Me to no switch.ender3 or switch.ender_3... device name is ender 3

**Comment by cmroche** [comment]
@LRTNZ is correct, this is a wifi switch. You will need to either remove it or replace with the id of a switch for your printer. It is not an entity exposed by this plugin.
