### ISSUE TITLE
Only seeing SOC temp and PSU Control

### ISSUE THREAD

**Issue by ripvega** [cmroche/OctoPrint-HomeAssistant#73]
I have 2 RPi4s running Octoprint and 2 printers. For both, in HA, I'm only seeing SOC temp and PSU control status.

What do I need to change?

**Comment by bepstein111** [comment]
same here. have followed all instructions in README, still only seeing SOC @ 32 F, nothing else.

**Comment by cmroche** [comment]
@ripvega @bepstein111  Just to be clear here, you are saying that you don't see a temperature for the Tool or the Bed? Is that still the case? IIRC, there was another plugin **OctoEverywhere** I think that was reported to have broken this at one point, can you confirm is you are using this extension please.

**Comment by bepstein111** [comment]
Neither. Here's what I get (I have disabled the only entity, that wasn't done automatically)
![2021-11-06 12_02_07-Configuration - Home Assistant](https://user-images.githubusercontent.com/6173863/140616000-29f890b7-aca5-420b-9897-93413ee8e47d.png)

**Comment by cmroche** [comment]
Couple things here to try:

1) Click MQTT Info, what are the sensors/topics that it lists?
2) Delete the device, then restart the printer, it should re-add the device.. do the sensors come back?
3) If all else fails, enable debug logging in HA & Octoprint and paste them as it may give us some hints to the cause.

Thanks
