### ISSUE TITLE
3.3.1 breaks HA integration for me

### ISSUE THREAD

**Issue by halfluck** [cmroche/OctoPrint-HomeAssistant#81]
Hey Guys,

since the 3.3.1 update my HA does not see any of my instances, i've tried a clean uninstall and new install of 3.3.1 with no luck, i've also tried installing cmroche version of OctoPrint-MQTT incase there was a compatibility issue with the main branch of OctoPrint-MQTT. When i roll back to 3.3.0 everything works as expected. 

HA Core 2021.10.5
OctoPrint 1.7.0 Python 3.7.3 OctoPi 0.18.0

Rob.

**Comment by cmroche** [comment]
That's very strange... but thanks for raising it, I'll look asap.
