### ISSUE TITLE
Use new button entities

### ISSUE THREAD

**Issue by 1RandomDev** [cmroche/OctoPrint-HomeAssistant#87]
Instead of switches for shutdown, reboot, start, stop, etc. the new button entities could now be used.

**Comment by cmroche** [comment]
Thanks for the suggestion, it makes a lot of sense with the new feature being available and I’ll look into this soon.

**Comment by tankdeer** [comment]
To add to this. I noticed recently that a number of the switches changed to the weird stateless lightning bolts in Home Assistant (Cancel is one). I suspect it's because the state topic & command topic are the same on those. Changing those a button would alleviate that issue as well
