### ISSUE TITLE
Add the ability to control the printer

### ISSUE THREAD

**Issue by cmroche** [cmroche/OctoPrint-HomeAssistant#9]
Seeing data is great and all, but you know what is better than read-only sensor? Being able to control your printer from home assistant!

Add the following types of actions, likely implemented as switches

- Emergency Stop, momentary switch
- Cancel Print, switch in on state when IsPrinting is On
- Pause/Resume, switch in on state when IsPrinting is On (3-state switch)

**Comment by W-Floyd** [comment]
I assume this would best be done using [MQTT Subscribe](https://plugins.octoprint.org/plugins/mqttsubscribe/), though I don't know how. Currently I use it to submit actions.

**Comment by cmroche** [comment]
I'm not sure yet and will need to look and see what that plugin offers before making a decision. It's possible that the setup I need is sufficiently simple that it would not justify the external dependency.
